-- To insert data into db execute the following command from the terminal
-- mysql -u root -p < server/database/db-init/mock-data/services.sql
USE bricolyDB;

INSERT INTO services (service, category_id) VALUES ('Leaking Pipes', 1);
INSERT INTO services (service, category_id) VALUES ('Night Guards', 2);
INSERT INTO services (service, category_id) VALUES ('Install or replace an elevator', 3);
INSERT INTO services (service, category_id) VALUES ('Exterior Painting', 4);
INSERT INTO services (service, category_id) VALUES ('Small electrical work', 5);
INSERT INTO services (service, category_id) VALUES ('Air Conditioners', 6);
INSERT INTO services (service, category_id) VALUES ('Household - Cleaning of premises', 7);
INSERT INTO services (service, category_id) VALUES ('Interior door', 8);
INSERT INTO services (service, category_id) VALUES ('Fencing', 9);
INSERT INTO services (service, category_id) VALUES ('Facade treatment', 10);
INSERT INTO services (service, category_id) VALUES ('Real estate treatment or diagnosis', 11);
INSERT INTO services (service, category_id) VALUES ('Heat pump', 12);
INSERT INTO services (service, category_id) VALUES ('Full bathroom installation', 13);
INSERT INTO services (service, category_id) VALUES ('Home entertainment', 14);
INSERT INTO services (service, category_id) VALUES ('Water Systems', 1);
INSERT INTO services (service, category_id) VALUES ('Alarm Systems', 2);
INSERT INTO services (service, category_id) VALUES ('Install or replace a freight elevator', 3);
INSERT INTO services (service, category_id) VALUES ('Interior Painting', 4);
INSERT INTO services (service, category_id) VALUES ('Inside lighting', 5);
INSERT INTO services (service, category_id) VALUES ('Refrigerators', 6);
INSERT INTO services (service, category_id) VALUES ('Chimney sweep', 7);
INSERT INTO services (service, category_id) VALUES ('Bodyguard', 8);
INSERT INTO services (service, category_id) VALUES ('Installation or renovation of a wooden terrace', 9);
INSERT INTO services (service, category_id) VALUES ('Foundation', 10);
INSERT INTO services (service, category_id) VALUES ('Solar panels / Photovoltaics', 11);
INSERT INTO services (service, category_id) VALUES ('Boiler - Heating', 12);
INSERT INTO services (service, category_id) VALUES ('Sanitary facilities', 13);
INSERT INTO services (service, category_id) VALUES ('Kitchen appliances', 14);
INSERT INTO services (service, category_id) VALUES ('Unclogging', 1);
INSERT INTO services (service, category_id) VALUES ('Surveillance Cameras', 2);
INSERT INTO services (service, category_id) VALUES ('Mini wastewater treatment plant', 1);
INSERT INTO services (service, category_id) VALUES ('Paper Hanging', 4);
INSERT INTO services (service, category_id) VALUES ('Computer cabling', 5);
INSERT INTO services (service, category_id) VALUES ('Central ACs', 6);
INSERT INTO services (service, category_id) VALUES ('Carpet cleaning', 7);
INSERT INTO services (service, category_id) VALUES ('Glass replacement', 8);
INSERT INTO services (service, category_id) VALUES ('Garden and green space maintenance', 9);
INSERT INTO services (service, category_id) VALUES ('Water treatment', 10);
INSERT INTO services (service, category_id) VALUES ('Energy performance diagnosis', 11);
INSERT INTO services (service, category_id) VALUES ('Wood stove', 12);
INSERT INTO services (service, category_id) VALUES ('WC installation', 13);
INSERT INTO services (service, category_id) VALUES ('Mobile devices', 14);
INSERT INTO services (service, category_id) VALUES ('Drainage', 1);
INSERT INTO services (service, category_id) VALUES ('entry lock', 2);
INSERT INTO services (service, category_id) VALUES ('Installation of spa bath, SPA and well-being', 1);
INSERT INTO services (service, category_id) VALUES ('Spray Painting', 4);
INSERT INTO services (service, category_id) VALUES ('Exterior lighting', 5);
INSERT INTO services (service, category_id) VALUES ('Cleaning - Washing of windows', 7);
INSERT INTO services (service, category_id) VALUES ('Install or replace a lock', 8);
INSERT INTO services (service, category_id) VALUES ('Pruning', 9);
INSERT INTO services (service, category_id) VALUES ('Riprap', 10);
INSERT INTO services (service, category_id) VALUES ('Wind turbine', 11);
INSERT INTO services (service, category_id) VALUES ('Installation - replacement of radiators', 12);
INSERT INTO services (service, category_id) VALUES ('Lead diagnosis or gas installation diagnosis', 11);
INSERT INTO services (service, category_id) VALUES ('Garden machinery', 14);
INSERT INTO services (service, category_id) VALUES ('Sewerage ', 1);
INSERT INTO services (service, category_id) VALUES ('Pool security', 2);
INSERT INTO services (service, category_id) VALUES ('Install or replace a stairlift', 3);
INSERT INTO services (service, category_id) VALUES ('Antenna and satellite', 5);
INSERT INTO services (service, category_id) VALUES ('Cars and vehicule cleaning', 7);
INSERT INTO services (service, category_id) VALUES ('Store', 8);
INSERT INTO services (service, category_id) VALUES ('Paving', 9);
INSERT INTO services (service, category_id) VALUES ('Cladding', 10);
INSERT INTO services (service, category_id) VALUES ('Solar water heater', 11);
INSERT INTO services (service, category_id) VALUES ('Underfloor heating', 12);
INSERT INTO services (service, category_id) VALUES ('Smoke extraction', 2);
INSERT INTO services (service, category_id) VALUES ('Other electronicals', 14);
INSERT INTO services (service, category_id) VALUES ('Fogger', 1);
INSERT INTO services (service, category_id) VALUES ('Interior design or architect', 10);
INSERT INTO services (service, category_id) VALUES ('Big work', 10);
INSERT INTO services (service, category_id) VALUES ('Intercom / Videophone', 5);
INSERT INTO services (service, category_id) VALUES ('Garage construction', 10);
INSERT INTO services (service, category_id) VALUES ('Window shop', 8);
INSERT INTO services (service, category_id) VALUES ('Pergola', 9);
INSERT INTO services (service, category_id) VALUES ('Building construction', 10);
INSERT INTO services (service, category_id) VALUES ('Electrical installation diagnosis', 11);
INSERT INTO services (service, category_id) VALUES ('Fireplace insert', 12);
INSERT INTO services (service, category_id) VALUES ('Guarding / Surveillance company', 2);
INSERT INTO services (service, category_id) VALUES ('Home appliances replacement', 14);
INSERT INTO services (service, category_id) VALUES ('water fountain', 1);
INSERT INTO services (service, category_id) VALUES ('Fire alarm', 2);
INSERT INTO services (service, category_id) VALUES ('Elevators maintenance', 3);
INSERT INTO services (service, category_id) VALUES ('Telephone wiring', 5);
INSERT INTO services (service, category_id) VALUES ('Small masonry work', 10);
INSERT INTO services (service, category_id) VALUES ('Roof window', 8);
INSERT INTO services (service, category_id) VALUES ('Swimming pool installation', 9);
INSERT INTO services (service, category_id) VALUES ('Water treatment', 10);
INSERT INTO services (service, category_id) VALUES ('Sanitation installation diagnosis', 11);
INSERT INTO services (service, category_id) VALUES ('Radiant ceiling', 12);
INSERT INTO services (service, category_id) VALUES ('Reversible climate control', 6);
INSERT INTO services (service, category_id) VALUES ('Laundry utilities', 14);
INSERT INTO services (service, category_id) VALUES ('Small plumbing jobs', 1);
INSERT INTO services (service, category_id) VALUES ('Flood barrier', 2);